language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t alexpil/docker-react -f Dockerfile.dev .
# All the commands that needs to run 
script:
  - docker run -e CI=true alexpil/docker-react npm run test